name: CI

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test  # 指定使用 test 环境
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - run: |
          # pnpm config set registry https://registry.npmmirror.com
          pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          SOURCE: ./dist/
          TARGET: ${{ vars.TARGET }}
